### ISSUE TITLE
Linsear Write Formula

### ISSUE THREAD

**Issue by slingload** [prosegrinder/python-prosegrinder#8]
It would be great to have the Linsear Write Formula added to the ReadabilityScores class. 
https://en.wikipedia.org/wiki/Linsear_Write

**Comment by davidlday** [comment]
I appreciated the follow-up email, btw. 😄

**Comment by davidlday** [comment]
The formula on Wikipedia is inconsistent with other implementations / sources:

* https://github.com/cdimascio/py-readability-metrics/blob/8905ceeaa05e68d9fb9bc0aa58cb1428ea2e0904/readability/scorers/linsear_write.py#L34
* https://github.com/unDocUMeantIt/koRpus/blob/dc5c4edf6d343c3a152e4eabcfa6c78dab1d7a1a/R/koRpus-internal.rdb.formulae.R#L1219
* https://web.archive.org/web/20081224172749/http://www.oleandersolutions.com:80/linsearwrite.html
* https://www.testbig.com/forum/linsear-write-formula

Wikipedia says to subtract 1 if the raw score is over 20, these other references subtract 2. Unless you have other references that say subtracting 1 is correct, I'll subtract 2 to stay consistent.

**Comment by slingload** [comment]
> The formula on Wikipedia is inconsistent with other implementations / sources:
> 
>     * https://github.com/cdimascio/py-readability-metrics/blob/8905ceeaa05e68d9fb9bc0aa58cb1428ea2e0904/readability/scorers/linsear_write.py#L34
> 
>     * https://github.com/unDocUMeantIt/koRpus/blob/dc5c4edf6d343c3a152e4eabcfa6c78dab1d7a1a/R/koRpus-internal.rdb.formulae.R#L1219
> 
>     * https://web.archive.org/web/20081224172749/http://www.oleandersolutions.com:80/linsearwrite.html
> 
>     * https://www.testbig.com/forum/linsear-write-formula
> 
> 
> Wikipedia says to subtract 1 if the raw score is over 20, these other references subtract 2. Unless you have other references that say subtracting 1 is correct, I'll subtract 2 to stay consistent.

Sounds good to me!
